"""
    Octree <: AbstractNodeGenerationAlgorithm

Spacing-driven volume discretization algorithm.

**Note:** This is not solution-adaptive (AMR). Refinement is determined a priori
by a prescribed spacing function, not by computed solution features.

!!! note
    `Octree` is a **discretization algorithm** that generates volume fill points.
    [`TriangleOctree`](@ref) is a separate **spatial data structure** used internally
    for mesh geometry queries. They serve different purposes.

# Algorithm
Uses dual octrees internally:
- **Triangle octree**: Captures geometry (surfaces, curvature)
- **Node octree**: Spacing-driven subdivision where `h_box ≤ alpha * h_spacing(x)`

Points are generated by weighted allocation across octree leaves based on
local spacing requirements.

# Key Parameters
- `min_ratio`: Triangle octree resolution (default: auto from mesh complexity)
- `node_min_ratio`: Node octree resolution (default: auto from `spacing` if provided)
- `alpha`: Subdivision aggressiveness, `h_box ≤ alpha * h_spacing` (default: 2.0, use 1.0 for fine boundary layers)
- `placement`: `:random`, `:jittered`, or `:lattice` (default: `:random`)
- `boundary_oversampling`: Oversampling near boundaries (default: 2.0)

# Examples
```julia
# Automatic (recommended)
alg = Octree(mesh; spacing, alpha=1.0)
cloud = discretize(boundary, spacing; alg, max_points=100_000)

# Manual geometry resolution
alg = Octree(mesh; min_ratio=1e-3, spacing, alpha=1.0)
```
"""
struct Octree{M <: Manifold, C <: CRS, T <: Real} <: AbstractNodeGenerationAlgorithm
    triangle_octree::TriangleOctree{M, C, T}
    boundary_oversampling::Float64
    placement::Symbol
    alpha::Float64  # Subdivision aggressiveness: boxes are at most alpha*h_local
    node_min_ratio::T  # Node octree minimum box size ratio (can be much finer than triangle octree)
end

# Constructors
function Octree(
        triangle_octree::TriangleOctree{M, C, T};
        node_min_ratio::Union{Nothing, Real} = nothing,
        boundary_oversampling::Real = 2.0,
        placement::Symbol = :random,
        alpha::Real = 2.0,
    ) where {M, C, T}
    boundary_oversampling > 0 || throw(ArgumentError("boundary_oversampling must be positive"))
    placement in (:random, :jittered, :lattice) ||
        throw(ArgumentError("placement must be :random, :jittered, or :lattice"))
    alpha > 0 || throw(ArgumentError("alpha must be positive"))

    # Default: use triangle octree's min_ratio
    node_ratio = isnothing(node_min_ratio) ? triangle_octree.tree.min_ratio : T(node_min_ratio)

    return Octree{M, C, T}(
        triangle_octree,
        Float64(boundary_oversampling),
        placement,
        Float64(alpha),
        node_ratio
    )
end

function Octree(
        mesh::SimpleMesh{M, C};
        spacing::Union{Nothing, AbstractSpacing} = nothing,
        min_ratio::Union{Nothing, Real} = nothing,
        node_min_ratio::Union{Nothing, Real} = nothing,
        tolerance_relative::Real = 1.0e-6,
        boundary_oversampling::Real = 2.0,
        placement::Symbol = :random,
        alpha::Real = 2.0,
        verify_orientation::Bool = true,
    ) where {M, C}
    T = Float64

    # Triangle octree: geometry-based or user override
    geometry_min_ratio = isnothing(min_ratio) ? _auto_min_ratio(T, mesh) : T(min_ratio)
    triangle_octree = TriangleOctree(
        mesh;
        tolerance_relative,
        min_ratio = geometry_min_ratio,
        classify_leaves = true,
        verify_orientation,
    )

    # Node octree: spacing-aware automatic or user override
    node_ratio = if !isnothing(node_min_ratio)
        # User provided explicit node_min_ratio
        T(node_min_ratio)
    elseif !isnothing(spacing)
        # Compute from spacing
        h_min = _extract_min_spacing(spacing)
        if !isnothing(h_min)
            # Compute domain size (strip units to get Float64)
            bbox = Meshes.boundingbox(mesh)
            extents = bbox.max - bbox.min
            # Get maximum extent value, stripping units
            extent_values = [T(ustrip(extents[i])) for i in 1:length(extents)]
            max_extent = maximum(extent_values)

            # Node octree must resolve features alpha times smaller than minimum spacing
            # to properly capture spacing variations across the domain
            min_resolvable_size = h_min / T(alpha)
            T(min_resolvable_size) / max_extent
        else
            # Unknown spacing type, fall back to triangle octree ratio
            geometry_min_ratio
        end
    else
        # No spacing hint, use triangle octree ratio
        geometry_min_ratio
    end

    return Octree{M, C, T}(
        triangle_octree,
        Float64(boundary_oversampling),
        placement,
        Float64(alpha),
        node_ratio
    )
end

Octree(filepath::String; kwargs...) = Octree(GeoIO.load(filepath).geometry; kwargs...)

# ============================================================================
# Helper functions
# ============================================================================

"""
    _auto_min_ratio(::Type{T}, mesh) where {T}

Default triangle octree resolution: `1 / (4 * cbrt(n_triangles))`.

Factor of 4 (vs. 2) ensures accurate geometry in high-curvature regions.
Override with explicit `min_ratio` parameter if needed.
"""
function _auto_min_ratio(::Type{T}, mesh::SimpleMesh) where {T}
    n = Meshes.nelements(mesh)
    # Factor of 4 (rather than 2) for 2× finer subdivision
    # This ensures accurate geometry representation in high-curvature regions
    return inv(T(4) * cbrt(T(n)))
end

"""
    _extract_min_spacing(spacing)

Extract minimum spacing value from spacing object (field access, no sampling).
"""
function _extract_min_spacing(spacing::ConstantSpacing)
    return Float64(ustrip(spacing.Δx))
end

function _extract_min_spacing(spacing::BoundaryLayerSpacing)
    return Float64(ustrip(spacing.at_wall))
end

# Fallback for other spacing types: return nothing to indicate unknown
_extract_min_spacing(::AbstractSpacing) = nothing

"""
    _rand_point_in_box(bbox_min, bbox_max)

Generate a random point uniformly distributed in a bounding box.
"""
@inline function _rand_point_in_box(bbox_min::SVector{3, T}, bbox_max::SVector{3, T}) where {T}
    return bbox_min + rand(SVector{3, T}) .* (bbox_max - bbox_min)
end

"""
    _allocate_counts_by_volume(volumes, total_count; ensure_one=false)

Proportionally allocate counts to volumes using probabilistic rounding.
Fractional parts become selection probabilities, reducing clustering.
"""
function _allocate_counts_by_volume(
        volumes::Vector{T},
        total_count::Int;
        ensure_one::Bool = false,
    ) where {T <: Real}
    n = length(volumes)
    n == 0 && return Int[]
    total_count <= 0 && return zeros(Int, n)

    total_volume = sum(volumes; init = zero(T))
    weights = total_volume > zero(T) ? volumes ./ total_volume : fill(inv(T(n)), n)

    counts = zeros(Int, n)
    remaining = total_count

    if ensure_one && total_count >= n
        counts .= 1
        remaining -= n
    end

    remaining <= 0 && return counts

    expected = remaining .* weights
    base = floor.(Int, expected)
    counts .+= base

    unallocated_count = remaining - sum(base)
    if unallocated_count > 0
        fractional_parts = expected .- base
        # Probabilistic rounding distributes leftover points randomly weighted by
        # fractional parts. This avoids clustering when total_count << n (e.g., 10 points
        # across 1000 boxes). Each box's fractional part becomes its selection probability.
        total_fractional = sum(fractional_parts)
        cumulative = cumsum(fractional_parts)

        for _ in 1:unallocated_count
            r = rand(T) * total_fractional
            idx = searchsortedfirst(cumulative, r)
            idx = clamp(idx, 1, n)
            counts[idx] += 1
        end
    end

    return counts
end

"""
    _generate_points_in_box(bbox_min, bbox_max, n, placement)

Generate `n` points: `:random`, `:jittered` (stratified), or `:lattice` (grid).
"""
function _generate_points_in_box(
        bbox_min::SVector{3, T},
        bbox_max::SVector{3, T},
        n::Int,
        placement::Symbol,
    ) where {T <: Real}
    n <= 0 && return SVector{3, T}[]
    placement == :random && return [_rand_point_in_box(bbox_min, bbox_max) for _ in 1:n]

    # For :jittered and :lattice, use regular grid structure
    grid_divisions = ceil(Int, cbrt(n))  # n > 0 guaranteed by early return above
    cell_size = (bbox_max - bbox_min) / T(grid_divisions)
    pts = SVector{3, T}[]
    sizehint!(pts, n)

    for k in 0:(grid_divisions - 1), j in 0:(grid_divisions - 1), i in 0:(grid_divisions - 1)
        length(pts) >= n && break
        cell_min = bbox_min + SVector{3, T}(T(i), T(j), T(k)) .* cell_size
        pt = placement == :lattice ? cell_min + cell_size / T(2) : cell_min + rand(SVector{3, T}) .* cell_size
        push!(pts, pt)
    end

    return pts
end

# Note: Octree infrastructure (SpacingCriterion, build_node_octree, etc.)
# has been moved to src/octree/spacing_criterion.jl for better code organization

# ============================================================================
# Point generation
# ============================================================================

struct LeafGroup{T <: Real}
    indices::Vector{Int}
    weights::Vector{T}
end

function _collect_weighted_leaves(node_tree, classification, spacing)
    T = Float64
    interior, near_surface = LeafGroup(Int[], T[]), LeafGroup(Int[], T[])

    for leaf_idx in all_leaves(node_tree)
        cls = classification[leaf_idx]
        if cls == LEAF_INTERIOR || cls == LEAF_BOUNDARY
            # Get spacing at box center (imported from spacing_criterion.jl)
            center = box_center(node_tree, leaf_idx)
            h_local_raw = T(ustrip(spacing(Point(center...))))
            h_local = max(h_local_raw, sqrt(eps(T)))

            # Weight by volume-to-spacing ratio: larger boxes or finer spacing get more points
            box_volume = box_size(node_tree, leaf_idx)^3
            spacing_volume = h_local^3
            weight = box_volume / spacing_volume

            group = cls == LEAF_INTERIOR ? interior : near_surface
            push!(group.indices, leaf_idx)
            push!(group.weights, weight)
        end
    end

    return interior, near_surface
end

function _generate_from_leaves(leaves::LeafGroup, tree, n_points, placement)
    T = Float64
    counts = _allocate_counts_by_volume(leaves.weights, n_points)

    points = SVector{3, T}[]
    sizehint!(points, n_points)

    for (leaf_idx, n) in zip(leaves.indices, counts)
        n == 0 && continue
        bbox_min, bbox_max = box_bounds(tree, leaf_idx)
        append!(points, _generate_points_in_box(bbox_min, bbox_max, n, placement))
    end

    return points
end

# ============================================================================
# Main discretization interface
# ============================================================================

function _discretize_volume(
        _cloud::PointCloud{𝔼{3}, C},
        spacing::AbstractSpacing,
        alg::Octree;
        max_points = 1_000,
    ) where {C}
    isnothing(alg.triangle_octree.leaf_classification) &&
        throw(
        ArgumentError(
            "TriangleOctree must be built with classify_leaves=true. " *
                "Rebuild with: TriangleOctree(mesh; classify_leaves=true)"
        )
    )

    T = Float64

    # Build and classify node octree (using infrastructure from src/octree/spacing_criterion.jl)
    print("  Building node octree...")
    t1 = @elapsed node_tree = build_node_octree(alg.triangle_octree, spacing, alg.alpha, alg.node_min_ratio)
    n_leaves = length(collect(all_leaves(node_tree)))
    println(" done ($(n_leaves) leaves, $(round(t1, digits = 2))s)")

    print("  Classifying node octree leaves...")
    t2 = @elapsed classification = classify_node_octree(node_tree, alg.triangle_octree)
    println(" done ($(round(t2, digits = 2))s)")

    print("  Collecting weighted leaves...")
    t3 = @elapsed interior, near_surface = _collect_weighted_leaves(node_tree, classification, spacing)
    println(" done (interior: $(length(interior.indices)), near_surface: $(length(near_surface.indices)), $(round(t3, digits = 2))s)")

    # Allocate points proportionally to weighted volumes
    interior_total_weight = sum(interior.weights; init = zero(T))
    near_surface_total_weight = sum(near_surface.weights; init = zero(T))
    total_weight = interior_total_weight + near_surface_total_weight
    total_weight <= zero(T) && return PointVolume(Point{𝔼{3}, C}[])

    interior_ratio = interior_total_weight / total_weight
    n_interior = round(Int, max_points * interior_ratio)
    n_near_surface = max_points - n_interior
    println("  Allocating $n_interior interior + $n_near_surface near-surface points")

    # Generate points. Interior leaves are trusted after classify_node_octree
    # demotes any leaf overlapping a triangle-octree boundary leaf, so samples
    # drawn from LEAF_INTERIOR (and the deficit fill, which pulls from the same
    # pool) do not need a per-point isinside check.
    raw_points = SVector{3, T}[]
    sizehint!(raw_points, max_points)

    print("  Generating interior points...")
    t4 = @elapsed interior_points = _generate_from_leaves(interior, node_tree, n_interior, alg.placement)
    println(" done ($(length(interior_points)) points, $(round(t4, digits = 2))s)")
    append!(raw_points, interior_points)

    n_candidates = round(Int, n_near_surface * alg.boundary_oversampling)
    print("  Generating near-surface candidates...")
    t5 = @elapsed candidates = _generate_from_leaves(near_surface, node_tree, n_candidates, alg.placement)
    println(" done ($(length(candidates)) candidates, $(round(t5, digits = 2))s)")

    print("  Filtering candidates (isinside check)...")
    t6 = @elapsed begin
        inside_mask = isinside(candidates, alg.triangle_octree)
        target = n_interior + n_near_surface
        for i in eachindex(candidates)
            length(raw_points) >= target && break
            inside_mask[i] && push!(raw_points, candidates[i])
        end
    end
    n_accepted = length(raw_points) - length(interior_points)
    println(" done ($n_accepted accepted, $(round(t6, digits = 2))s)")

    # Fill deficit from interior leaves. No isinside needed — interior leaves
    # are guaranteed not to overlap any boundary triangle-octree leaf.
    if length(raw_points) < max_points
        deficit = max_points - length(raw_points)
        println("  Filling deficit of $deficit points...")
        cumulative_weights = isempty(interior.weights) ? T[] : cumsum(interior.weights)
        total_weight = isempty(cumulative_weights) ? zero(T) : cumulative_weights[end]

        if total_weight > zero(T)
            for _ in 1:deficit
                idx = clamp(searchsortedfirst(cumulative_weights, rand(T) * total_weight), 1, length(interior.indices))
                bbox_min, bbox_max = box_bounds(node_tree, interior.indices[idx])
                push!(raw_points, _rand_point_in_box(bbox_min, bbox_max))
            end
        end
    end

    # Convert to Point objects
    return PointVolume([Point(pt...) for pt in raw_points])
end
