"""
    Octree <: AbstractNodeGenerationAlgorithm

Spacing-driven volume discretization algorithm.

**Note:** This is not solution-adaptive (AMR). Refinement is determined a priori
by a prescribed spacing function, not by computed solution features.

!!! note
    `Octree` is a **discretization algorithm** that generates volume fill points.
    [`TriangleOctree`](@ref) is a separate **spatial data structure** used internally
    for mesh geometry queries. They serve different purposes.

# Algorithm
Uses dual octrees internally:
- **Triangle octree**: Captures geometry (surfaces, curvature)
- **Node octree**: Spacing-driven subdivision where `h_box ≤ alpha * h_spacing(x)`

Points are generated by weighted allocation across octree leaves based on
local spacing requirements.

# Key Parameters
- `min_ratio`: Triangle octree resolution (default: auto from mesh complexity)
- `node_min_ratio`: Node octree resolution (default: auto from `spacing` if provided)
- `alpha`: Subdivision aggressiveness, `h_box ≤ alpha * h_spacing` (default: 2.0, use 1.0 for fine boundary layers)
- `placement`: `:random`, `:jittered`, `:lattice`, or `:bridson` (default: `:random`; `:bridson` recommended for production)
- `bridson_factor`: Poisson-disk radius relative to `h(x)` for `:bridson` (default: 0.75)
- `boundary_oversampling`: Oversampling near boundaries (default: 2.0)

# Placement modes
`:random`, `:jittered`, and `:lattice` sample each octree leaf independently
(point counts allocated by leaf volume / local spacing). `:bridson` instead runs
a single global advancing-front Poisson-disk pass (Bridson 2007, graded to
`h(x)`) seeded from the boundary points: every generated point keeps a distance
of at least `min(rᵢ, rⱼ)` with `r = bridson_factor · h(x)` from every other
point — including the boundary — *by construction*. The front saturates at the
disk-packing density, so `max_points` acts as a cap, not a target; a warning is
emitted if the cap truncates the front before saturation (which would leave
unfilled regions).

`bridson_factor` (default 0.75) sets the disk radius relative to the local
spacing. A saturated 3D dart-throwing front packs ≈ 0.39 points per `r³`
(measured on this implementation, k = 30 attempts), so matching the prescribed
density `1/h³` requires `r ≈ 0.73·h`; the 0.75 default keeps the saturated
count just below the prescribed budget. Use `1.0` for strict `d_NN ≥ h`
Poisson-disk sampling — that yields ~45% fewer points than `1/h³` and starts
`repel`'s spacing-equilibrium force in its attractive branch, which degrades
rather than polishes the seeding (measured on the cavity gate).

# Examples
```julia
# Automatic (recommended)
alg = Octree(mesh; spacing, alpha=1.0)
cloud = discretize(boundary, spacing; alg, max_points=100_000)

# Manual geometry resolution
alg = Octree(mesh; min_ratio=1e-3, spacing, alpha=1.0)
```
"""
struct Octree{M <: Manifold, C <: CRS, T <: Real} <: AbstractNodeGenerationAlgorithm
    triangle_octree::TriangleOctree{M, C, T}
    boundary_oversampling::Float64
    placement::Symbol
    alpha::Float64  # Subdivision aggressiveness: boxes are at most alpha*h_local
    node_min_ratio::T  # Node octree minimum box size ratio (can be much finer than triangle octree)
    bridson_factor::Float64  # Poisson-disk radius relative to h(x) (placement = :bridson only)
end

# Constructors
function Octree(
        triangle_octree::TriangleOctree{M, C, T};
        node_min_ratio::Union{Nothing, Real} = nothing,
        boundary_oversampling::Real = 2.0,
        placement::Symbol = :random,
        alpha::Real = 2.0,
        bridson_factor::Real = 0.75,
    ) where {M, C, T}
    boundary_oversampling > 0 || throw(ArgumentError("boundary_oversampling must be positive"))
    placement in (:random, :jittered, :lattice, :bridson) ||
        throw(ArgumentError("placement must be :random, :jittered, :lattice, or :bridson"))
    alpha > 0 || throw(ArgumentError("alpha must be positive"))
    bridson_factor > 0 || throw(ArgumentError("bridson_factor must be positive"))

    # Default: use triangle octree's min_ratio
    node_ratio = isnothing(node_min_ratio) ? triangle_octree.tree.min_ratio : T(node_min_ratio)

    return Octree{M, C, T}(
        triangle_octree,
        Float64(boundary_oversampling),
        placement,
        Float64(alpha),
        node_ratio,
        Float64(bridson_factor)
    )
end

function Octree(
        mesh::SimpleMesh{M, C};
        spacing::Union{Nothing, AbstractSpacing} = nothing,
        min_ratio::Union{Nothing, Real} = nothing,
        node_min_ratio::Union{Nothing, Real} = nothing,
        tolerance_relative::Real = 1.0e-6,
        boundary_oversampling::Real = 2.0,
        placement::Symbol = :random,
        alpha::Real = 2.0,
        bridson_factor::Real = 0.75,
        verify_orientation::Bool = true,
    ) where {M, C}
    placement in (:random, :jittered, :lattice, :bridson) ||
        throw(ArgumentError("placement must be :random, :jittered, :lattice, or :bridson"))
    bridson_factor > 0 || throw(ArgumentError("bridson_factor must be positive"))
    T = Float64

    # Triangle octree: geometry-based or user override
    geometry_min_ratio = isnothing(min_ratio) ? _auto_min_ratio(T, mesh) : T(min_ratio)
    triangle_octree = TriangleOctree(
        mesh;
        tolerance_relative,
        min_ratio = geometry_min_ratio,
        classify_leaves = true,
        verify_orientation,
    )

    # Node octree: spacing-aware automatic or user override
    node_ratio = if !isnothing(node_min_ratio)
        # User provided explicit node_min_ratio
        T(node_min_ratio)
    elseif !isnothing(spacing)
        # Compute from spacing
        h_min = _extract_min_spacing(spacing)
        if !isnothing(h_min)
            # Compute domain size (strip units to get Float64)
            bbox = Meshes.boundingbox(mesh)
            extents = bbox.max - bbox.min
            # Get maximum extent value, stripping units
            extent_values = [T(ustrip(extents[i])) for i in 1:length(extents)]
            max_extent = maximum(extent_values)

            # Node octree must resolve features alpha times smaller than minimum spacing
            # to properly capture spacing variations across the domain
            min_resolvable_size = h_min / T(alpha)
            T(min_resolvable_size) / max_extent
        else
            # Unknown spacing type, fall back to triangle octree ratio
            geometry_min_ratio
        end
    else
        # No spacing hint, use triangle octree ratio
        geometry_min_ratio
    end

    return Octree{M, C, T}(
        triangle_octree,
        Float64(boundary_oversampling),
        placement,
        Float64(alpha),
        node_ratio,
        Float64(bridson_factor)
    )
end

Octree(filepath::String; kwargs...) = Octree(GeoIO.load(filepath).geometry; kwargs...)

# ============================================================================
# Helper functions
# ============================================================================

"""
    _auto_min_ratio(::Type{T}, mesh) where {T}

Default triangle octree resolution: `1 / (4 * cbrt(n_triangles))`.

Factor of 4 (vs. 2) ensures accurate geometry in high-curvature regions.
Override with explicit `min_ratio` parameter if needed.
"""
function _auto_min_ratio(::Type{T}, mesh::SimpleMesh) where {T}
    n = Meshes.nelements(mesh)
    # Factor of 4 (rather than 2) for 2× finer subdivision
    # This ensures accurate geometry representation in high-curvature regions
    return inv(T(4) * cbrt(T(n)))
end

"""
    _extract_min_spacing(spacing)

Extract minimum spacing value from spacing object (field access, no sampling).
"""
function _extract_min_spacing(spacing::ConstantSpacing)
    return Float64(ustrip(spacing.Δx))
end

function _extract_min_spacing(spacing::BoundaryLayerSpacing)
    return Float64(ustrip(spacing.at_wall))
end

# Fallback for other spacing types: return nothing to indicate unknown
_extract_min_spacing(::AbstractSpacing) = nothing

"""
    _rand_point_in_box(bbox_min, bbox_max)

Generate a random point uniformly distributed in a bounding box.
"""
@inline function _rand_point_in_box(bbox_min::SVector{3, T}, bbox_max::SVector{3, T}) where {T}
    return bbox_min + rand(SVector{3, T}) .* (bbox_max - bbox_min)
end

"""
    _allocate_counts_by_volume(volumes, total_count; ensure_one=false)

Proportionally allocate counts to volumes using probabilistic rounding.
Fractional parts become selection probabilities, reducing clustering.
"""
function _allocate_counts_by_volume(
        volumes::Vector{T},
        total_count::Int;
        ensure_one::Bool = false,
    ) where {T <: Real}
    n = length(volumes)
    n == 0 && return Int[]
    total_count <= 0 && return zeros(Int, n)

    total_volume = sum(volumes; init = zero(T))
    weights = total_volume > zero(T) ? volumes ./ total_volume : fill(inv(T(n)), n)

    counts = zeros(Int, n)
    remaining = total_count

    if ensure_one && total_count >= n
        counts .= 1
        remaining -= n
    end

    remaining <= 0 && return counts

    expected = remaining .* weights
    base = floor.(Int, expected)
    counts .+= base

    unallocated_count = remaining - sum(base)
    if unallocated_count > 0
        fractional_parts = expected .- base
        # Probabilistic rounding distributes leftover points randomly weighted by
        # fractional parts. This avoids clustering when total_count << n (e.g., 10 points
        # across 1000 boxes). Each box's fractional part becomes its selection probability.
        total_fractional = sum(fractional_parts)
        cumulative = cumsum(fractional_parts)

        for _ in 1:unallocated_count
            r = rand(T) * total_fractional
            idx = searchsortedfirst(cumulative, r)
            idx = clamp(idx, 1, n)
            counts[idx] += 1
        end
    end

    return counts
end

"""
    _generate_points_in_box(bbox_min, bbox_max, n, placement)

Generate `n` points: `:random`, `:jittered` (stratified), or `:lattice` (grid).
"""
function _generate_points_in_box(
        bbox_min::SVector{3, T},
        bbox_max::SVector{3, T},
        n::Int,
        placement::Symbol,
    ) where {T <: Real}
    n <= 0 && return SVector{3, T}[]
    placement == :random && return [_rand_point_in_box(bbox_min, bbox_max) for _ in 1:n]

    # For :jittered and :lattice, use regular grid structure
    grid_divisions = ceil(Int, cbrt(n))  # n > 0 guaranteed by early return above
    cell_size = (bbox_max - bbox_min) / T(grid_divisions)
    pts = SVector{3, T}[]
    sizehint!(pts, n)

    for k in 0:(grid_divisions - 1), j in 0:(grid_divisions - 1), i in 0:(grid_divisions - 1)
        length(pts) >= n && break
        cell_min = bbox_min + SVector{3, T}(T(i), T(j), T(k)) .* cell_size
        pt = placement == :lattice ? cell_min + cell_size / T(2) : cell_min + rand(SVector{3, T}) .* cell_size
        push!(pts, pt)
    end

    return pts
end

# Note: Octree infrastructure (SpacingCriterion, build_node_octree, etc.)
# has been moved to src/octree/spacing_criterion.jl for better code organization

# ============================================================================
# Point generation
# ============================================================================

struct LeafGroup{T <: Real}
    indices::Vector{Int}
    weights::Vector{T}
end

function _collect_weighted_leaves(node_tree, classification, spacing)
    T = Float64
    interior, near_surface = LeafGroup(Int[], T[]), LeafGroup(Int[], T[])

    for leaf_idx in all_leaves(node_tree)
        cls = classification[leaf_idx]
        if cls == LEAF_INTERIOR || cls == LEAF_BOUNDARY
            # Get spacing at box center (imported from spacing_criterion.jl)
            center = box_center(node_tree, leaf_idx)
            h_local_raw = T(ustrip(spacing(Point(center...))))
            h_local = max(h_local_raw, sqrt(eps(T)))

            # Weight by volume-to-spacing ratio: larger boxes or finer spacing get more points
            box_volume = box_size(node_tree, leaf_idx)^3
            spacing_volume = h_local^3
            weight = box_volume / spacing_volume

            group = cls == LEAF_INTERIOR ? interior : near_surface
            push!(group.indices, leaf_idx)
            push!(group.weights, weight)
        end
    end

    return interior, near_surface
end

function _generate_from_leaves(leaves::LeafGroup, tree, n_points, placement)
    T = Float64
    counts = _allocate_counts_by_volume(leaves.weights, n_points)

    points = SVector{3, T}[]
    sizehint!(points, n_points)

    for (leaf_idx, n) in zip(leaves.indices, counts)
        n == 0 && continue
        bbox_min, bbox_max = box_bounds(tree, leaf_idx)
        append!(points, _generate_points_in_box(bbox_min, bbox_max, n, placement))
    end

    return points
end

# ============================================================================
# Bridson graded Poisson-disk sampling (placement = :bridson)
# ============================================================================
#
# Global advancing-front Poisson-disk sampling (Bridson 2007), graded to the
# spacing function h(x). Unlike the per-leaf placement modes, separation is
# enforced *across* octree leaves through one background bucket grid spanning
# the whole domain — per-leaf sampling without a cross-leaf constraint is
# precisely why stratified jitter has the same raw spacing CV as uniform
# Poisson. The grid cell size is h_min/√3 so that, at constant spacing, a cell
# holds at most one accepted point; buckets are linked lists because boundary
# seeds may be mutually closer than h (only candidates are tested, never the
# seeds against each other).

struct _BridsonGrid{T <: Real}
    gmin::SVector{3, T}
    cell::T
    dims::NTuple{3, Int}
    head::Vector{Int32}  # per-cell index of the most recent point, 0 = empty
    nxt::Vector{Int32}   # per-point link to the previous point in its cell
end

function _BridsonGrid(gmin::SVector{3, T}, gmax::SVector{3, T}, h_min::T) where {T}
    cell = h_min / sqrt(T(3))
    extent = gmax - gmin
    # Memory guard: coarsen the grid if the domain is huge relative to h_min.
    # Correctness is unaffected (buckets hold multiple points); only the
    # neighbor scan gets slightly wider.
    max_cells = 1 << 27
    n_est = prod(max(ceil(x / cell), 1.0) for x in extent)
    if n_est > max_cells
        cell *= T(cbrt(n_est / max_cells))
    end
    dims = ntuple(d -> max(ceil(Int, extent[d] / cell), 1), 3)
    return _BridsonGrid{T}(gmin, cell, dims, zeros(Int32, prod(dims)), Int32[])
end

@inline function _grid_cell(g::_BridsonGrid{T}, p::SVector{3, T}) where {T}
    return ntuple(3) do d
        clamp(floor(Int, (p[d] - g.gmin[d]) / g.cell) + 1, 1, g.dims[d])
    end
end

@inline _grid_lin(g::_BridsonGrid, i, j, k) = i + g.dims[1] * ((j - 1) + g.dims[2] * (k - 1))

"""
    _grid_insert!(grid, p)

Insert the point with the next sequential index into its bucket. Points must be
inserted in index order (1, 2, …) — the link vector grows by one per call.
"""
function _grid_insert!(g::_BridsonGrid{T}, p::SVector{3, T}) where {T}
    l = _grid_lin(g, _grid_cell(g, p)...)
    push!(g.nxt, g.head[l])
    g.head[l] = Int32(length(g.nxt))
    return nothing
end

"""
    _bridson_separated(grid, pts, rs, c, r_c) -> Bool

`true` when candidate `c` (local disk radius `r_c`) is at least `min(r_c, r_q)`
away from every accepted point `q`. Any rejecting point lies within `r_c` of
`c`, so scanning buckets within `r_c` suffices.
"""
function _bridson_separated(
        g::_BridsonGrid{T}, pts::Vector{SVector{3, T}}, rs::Vector{T},
        c::SVector{3, T}, r_c::T,
    ) where {T}
    ci, cj, ck = _grid_cell(g, c)
    m = ceil(Int, r_c / g.cell)
    @inbounds for k in max(1, ck - m):min(g.dims[3], ck + m),
            j in max(1, cj - m):min(g.dims[2], cj + m),
            i in max(1, ci - m):min(g.dims[1], ci + m)

        idx = g.head[_grid_lin(g, i, j, k)]
        while idx != 0
            r = min(r_c, rs[idx])
            sum(abs2, c - pts[idx]) < r * r && return false
            idx = g.nxt[idx]
        end
    end
    return true
end

"""
    _bridson_inside(c, node_tree, classification, tri_octree) -> Bool

Domain test for a Bridson candidate, mirroring the trust rules of the per-leaf
path: interior node-octree leaves are accepted outright, boundary leaves get an
exact `isinside` check, exterior leaves (and anything outside the mesh bbox)
are rejected.
"""
@inline function _bridson_inside(
        c::SVector{3, T}, node_tree, classification, tri_octree,
    ) where {T}
    (any(c .<= tri_octree.mesh_bbox_min) || any(c .>= tri_octree.mesh_bbox_max)) &&
        return false
    cls = classification[find_leaf(node_tree, c)]
    cls == LEAF_INTERIOR && return true
    cls == LEAF_BOUNDARY && return isinside(c, tri_octree)
    return false
end

"""
    _non_exterior_leaves(node_tree, classification) -> Vector{Int}

Indices of every leaf that is not classified `LEAF_EXTERIOR` (interior +
boundary). The shared leaf set behind the spacing-integral helpers below.
"""
function _non_exterior_leaves(node_tree, classification)
    leaves = Int[]
    for idx in 1:node_tree.num_boxes[]
        is_leaf(node_tree, idx) || continue
        classification[idx] == LEAF_EXTERIOR && continue
        push!(leaves, idx)
    end
    return leaves
end

"""
    _bridson_h_min(node_tree, classification, spacing) -> Float64

Minimum spacing over non-exterior leaf centers — sets the background grid
resolution for graded spacing.
"""
function _bridson_h_min(node_tree, classification, spacing)
    T = Float64
    leaves = _non_exterior_leaves(node_tree, classification)
    isempty(leaves) && throw(ArgumentError("no non-exterior leaves: cannot run Bridson sampling"))
    h_min = tmapreduce(min, leaves) do idx
        _spacing_value(T, spacing, box_center(node_tree, idx))
    end
    return max(h_min, sqrt(eps(T)))
end

"""
    _estimate_volume_points(node_tree, classification, spacing) -> Int

Estimate the saturated graded-fill point count as `⌈1.1 · ∑ box_volume/h(x)³⌉`
over non-exterior leaves — the discrete spacing integral `∫ 1/h³ dx`, padded
10 %. Used as the automatic `max_points` cap for the `Octree` algorithm when the
caller leaves it unset.
"""
function _estimate_volume_points(node_tree, classification, spacing)
    T = Float64
    leaves = _non_exterior_leaves(node_tree, classification)
    isempty(leaves) && return 0
    integral = tmapreduce(+, leaves) do idx
        h = max(_spacing_value(T, spacing, box_center(node_tree, idx)), sqrt(eps(T)))
        box_size(node_tree, idx)^3 / h^3
    end
    return ceil(Int, 1.1 * integral)
end

"""
    _generate_bridson(node_tree, classification, tri_octree, spacing, seeds,
                      max_points; factor=0.75, k_attempts=30)
        -> Vector{SVector{3,Float64}}

Graded Bridson Poisson-disk sampling of the domain volume with disk radius
`factor · h(x)` (see the `Octree` docstring for the choice of `factor`).
`seeds` (boundary points) initialize the advancing front and occupy the
background grid so volume points keep their distance from the wall, but are
not returned. The front runs until saturation or until `max_points` volume
points exist; truncation warns because it leaves the far side of the front
unfilled.
"""
function _generate_bridson(
        node_tree, classification, tri_octree, spacing,
        seeds::Vector{SVector{3, T}}, max_points::Int;
        factor::Real = 0.75,
        k_attempts::Int = 30,
    ) where {T <: Real}
    f = T(factor)
    r_min = f * _bridson_h_min(node_tree, classification, spacing)
    grid = _BridsonGrid(tri_octree.mesh_bbox_min, tri_octree.mesh_bbox_max, r_min)

    pts = copy(seeds)
    rs = [f * _spacing_value(T, spacing, p) for p in pts]
    sizehint!(pts, length(seeds) + max_points)
    sizehint!(rs, length(seeds) + max_points)
    foreach(p -> _grid_insert!(grid, p), pts)
    active = collect(1:length(pts))
    n_seeds = length(seeds)

    # Boundary-free start: seed the front from the first valid leaf center
    # (interior leaves first — they need no isinside check).
    if isempty(active)
        for want_interior in (true, false), leaf_idx in all_leaves(node_tree)
            cls = classification[leaf_idx]
            (want_interior ? cls == LEAF_INTERIOR : cls == LEAF_BOUNDARY) || continue
            c = box_center(node_tree, leaf_idx)
            _bridson_inside(c, node_tree, classification, tri_octree) || continue
            push!(pts, c)
            push!(rs, f * _spacing_value(T, spacing, c))
            _grid_insert!(grid, c)
            push!(active, length(pts))
            break
        end
        isempty(active) && return SVector{3, T}[]
    end

    n_generated = length(pts) - n_seeds
    while !isempty(active) && n_generated < max_points
        ai = rand(1:length(active))
        a = active[ai]
        found = false
        for _ in 1:k_attempts
            ρ = rs[a] * (1 + rand(T))
            d = randn(SVector{3, T})
            c = pts[a] + ρ * (d / norm(d))
            _bridson_inside(c, node_tree, classification, tri_octree) || continue
            r_c = f * _spacing_value(T, spacing, c)
            _bridson_separated(grid, pts, rs, c, r_c) || continue
            push!(pts, c)
            push!(rs, r_c)
            _grid_insert!(grid, c)
            push!(active, length(pts))
            n_generated += 1
            found = true
            n_generated >= max_points && break
        end
        if !found
            active[ai] = active[end]
            pop!(active)
        end
    end

    if n_generated >= max_points && !isempty(active)
        # The cap aborts the sweep with unprocessed entries still in `active`,
        # so a non-empty front alone cannot distinguish "cap == saturation
        # count" (benign: scattered single-dart holes at most) from a genuine
        # truncation that leaves uncovered volume. Probe with a bounded burst
        # of extra darts (nothing inserted): any acceptable candidate proves
        # room remains and the warning is real.
        truncated = false
        for _ in 1:200
            a = active[rand(1:length(active))]
            ρ = rs[a] * (1 + rand(T))
            d = randn(SVector{3, T})
            c = pts[a] + ρ * (d / norm(d))
            _bridson_inside(c, node_tree, classification, tri_octree) || continue
            r_c = f * _spacing_value(T, spacing, c)
            _bridson_separated(grid, pts, rs, c, r_c) || continue
            truncated = true
            break
        end
        truncated &&
            @warn "Bridson front truncated by max_points before saturation — parts of the domain may be unfilled" max_points
    end

    return pts[(n_seeds + 1):end]
end

# ============================================================================
# Main discretization interface
# ============================================================================

function _discretize_volume(
        _cloud::PointCloud{𝔼{3}, C},
        spacing::AbstractSpacing,
        alg::Octree;
        max_points::Union{Int, Nothing} = nothing,
    ) where {C}
    isnothing(alg.triangle_octree.leaf_classification) &&
        throw(
        ArgumentError(
            "TriangleOctree must be built with classify_leaves=true. " *
                "Rebuild with: TriangleOctree(mesh; classify_leaves=true)"
        )
    )

    T = Float64

    # Build and classify node octree (using infrastructure from src/octree/spacing_criterion.jl)
    print("  Building node octree...")
    t1 = @elapsed node_tree = build_node_octree(alg.triangle_octree, spacing, alg.alpha, alg.node_min_ratio)
    n_leaves = length(collect(all_leaves(node_tree)))
    println(" done ($(n_leaves) leaves, $(round(t1, digits = 2))s)")

    print("  Classifying node octree leaves...")
    t2 = @elapsed classification = classify_node_octree(node_tree, alg.triangle_octree)
    println(" done ($(round(t2, digits = 2))s)")

    # Resolve the automatic point-count cap: when the caller leaves max_points
    # unset, estimate it from the spacing integral (∑ box_volume/h³).
    if isnothing(max_points)
        max_points = _estimate_volume_points(node_tree, classification, spacing)
        println("  Auto-estimated max_points = $max_points")
    end

    # :bridson is a single global pass — no per-leaf allocation, candidate
    # filtering, or deficit fill (each would break the separation guarantee).
    if alg.placement == :bridson
        seeds = [_extract_vertex(T, pt) for pt in points(boundary(_cloud))]
        print("  Bridson sampling ($(length(seeds)) boundary seeds)...")
        t3 = @elapsed vol_points = _generate_bridson(
            node_tree, classification, alg.triangle_octree, spacing, seeds, max_points;
            factor = alg.bridson_factor,
        )
        println(" done ($(length(vol_points)) points, $(round(t3, digits = 2))s)")
        return PointVolume([Point(pt...) for pt in vol_points])
    end

    print("  Collecting weighted leaves...")
    t3 = @elapsed interior, near_surface = _collect_weighted_leaves(node_tree, classification, spacing)
    println(" done (interior: $(length(interior.indices)), near_surface: $(length(near_surface.indices)), $(round(t3, digits = 2))s)")

    # Allocate points proportionally to weighted volumes
    interior_total_weight = sum(interior.weights; init = zero(T))
    near_surface_total_weight = sum(near_surface.weights; init = zero(T))
    total_weight = interior_total_weight + near_surface_total_weight
    total_weight <= zero(T) && return PointVolume(Point{𝔼{3}, C}[])

    interior_ratio = interior_total_weight / total_weight
    n_interior = round(Int, max_points * interior_ratio)
    n_near_surface = max_points - n_interior
    println("  Allocating $n_interior interior + $n_near_surface near-surface points")

    # Generate points. Interior leaves are trusted after classify_node_octree
    # demotes any leaf overlapping a triangle-octree boundary leaf, so samples
    # drawn from LEAF_INTERIOR (and the deficit fill, which pulls from the same
    # pool) do not need a per-point isinside check.
    raw_points = SVector{3, T}[]
    sizehint!(raw_points, max_points)

    print("  Generating interior points...")
    t4 = @elapsed interior_points = _generate_from_leaves(interior, node_tree, n_interior, alg.placement)
    println(" done ($(length(interior_points)) points, $(round(t4, digits = 2))s)")
    append!(raw_points, interior_points)

    n_candidates = round(Int, n_near_surface * alg.boundary_oversampling)
    print("  Generating near-surface candidates...")
    t5 = @elapsed candidates = _generate_from_leaves(near_surface, node_tree, n_candidates, alg.placement)
    println(" done ($(length(candidates)) candidates, $(round(t5, digits = 2))s)")

    print("  Filtering candidates (isinside check)...")
    t6 = @elapsed begin
        inside_mask = isinside(candidates, alg.triangle_octree)
        target = n_interior + n_near_surface
        for i in eachindex(candidates)
            length(raw_points) >= target && break
            inside_mask[i] && push!(raw_points, candidates[i])
        end
    end
    n_accepted = length(raw_points) - length(interior_points)
    println(" done ($n_accepted accepted, $(round(t6, digits = 2))s)")

    # Fill deficit from interior leaves. No isinside needed — interior leaves
    # are guaranteed not to overlap any boundary triangle-octree leaf.
    if length(raw_points) < max_points
        deficit = max_points - length(raw_points)
        println("  Filling deficit of $deficit points...")
        cumulative_weights = isempty(interior.weights) ? T[] : cumsum(interior.weights)
        total_weight = isempty(cumulative_weights) ? zero(T) : cumulative_weights[end]

        if total_weight > zero(T)
            for _ in 1:deficit
                idx = clamp(searchsortedfirst(cumulative_weights, rand(T) * total_weight), 1, length(interior.indices))
                bbox_min, bbox_max = box_bounds(node_tree, interior.indices[idx])
                push!(raw_points, _rand_point_in_box(bbox_min, bbox_max))
            end
        end
    end

    # Convert to Point objects
    return PointVolume([Point(pt...) for pt in raw_points])
end

"""
    _ensure_float64_boundary(bnd::PointBoundary) -> PointBoundary

Promote a boundary with a non-Float64 machine type to Float64, preserving
surface names, normals, and areas. Binary STL stores Float32 by spec, while
the Octree algorithm generates Float64 volume points and `PointCloud`
requires one CRS across boundary and volume — without promotion the cloud
assembly fails. Returns `bnd` unchanged when already Float64.
"""
function _ensure_float64_boundary(bnd::PointBoundary{M, C}) where {M, C}
    CoordRefSystems.mactype(C) === Float64 && return bnd
    promoted = [
        name => PointSurface(
            [Point((1.0 .* to(p))...) for p in points(surf)],
            collect(normal(surf)),
            [1.0 * a for a in area(surf)],
        ) for (name, surf) in namedsurfaces(bnd)
    ]
    isempty(promoted) && return bnd
    surfaces = LittleDict{Symbol, typeof(last(first(promoted)))}(promoted...)
    return PointBoundary(surfaces)
end
